title: YONG HUANG
email: yh849@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: YONG HUANG # add your name
author-pic: yong.png
about-author:  Hi, I'm Yong Huang(黄勇), a master student studying Information Science with a concentration on Healthcare at Cornell Tech, Cornell University.
        Welcome to my site, I am very lucky to be advised by Professor Deborah Estrin. I’m extremely privileged to have
        met many wonderful people who have inspired my work and passions; I owe much of myself to their kindness, compassion, and ardour.
        If you feel like getting in touch with me, feel free to send me an email.

# Contact links
email: yh849@cornell.edu # Add your Email address
phone: 9293191866 # Add your Phone number
website: yonglhuang.com # Add your website, do not add http://
linkedin: https://www.linkedin.com/in/yong-huang-37165616a/ # Add your Linkedin handle
github: acneyouth1996 # Add your Github handle
twitter: '@HuangYo64614728' # Add your Twitter handle
facebook:  ct_hy_1996 # Add your Facebook handle
instagram: ct_hy_1996# Add your Instagram handle


# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: yonglhuang-com # Add your discus identifier

mathjax:   true

# Tracker
# analytics: # Google Analytics
analytics: UA-139551113-1

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
